### ISSUE TITLE
Is JSONObject queryInfoJSON is used just to get the Query String?

### ISSUE THREAD

**Issue by iRimo18** [ankitdixit/prestoeventlistener#1]
I guess the JSONObject queryInfoJSON is used just to get the Query String, whereas you could use QueryMetadata of QueryCreatedEvent to get the Query.

Is there any other purpose of asking for raw json (i.e, localhost/v1/query) ?
Or am I missing any point?

**Comment by ankitdixit** [comment]
@iRimo18 Yes, you are right. I wanted the queryInfo at queryCompletionEvent hence the call.
